### PR TITLE
[Linux] Some fixes/changes for packaging support

### LINKED ISSUE #3: Linux launcher will only run from terminal
CML on linux requires running from the terminal to function. 

Doubleclicking does not do anything even with correct user group and executable permissions set, replies to previous reports of this issues on the chromapper discord confirmed this should not be the case.

### PR DESCRIPTION
**Pull request by FallenCharlotte**
1. Fixes CML crashing without an interactive terminal (fixes #3)
2. Allows the download directory to be set via command-line argument

### CODE REVIEW

File: Linux/LinuxSpecific.cs [hunk 1]
```diff
@@ -50,17 +50,20 @@ public bool UseCDN()
...
+
+            var currentLineCursor = Console.CursorTop;
+            if (currentLineCursor - lineNumber > 0) {
+                Console.SetCursorPosition(0, currentLineCursor - lineNumber);
+                Console.Write(newText); Console.WriteLine(new string(' ', Console.WindowWidth - newText.Length));
+                Console.SetCursorPosition(0, currentLineCursor);
+                return;
+            }
         }
+        catch (Exception) { }
```
Comment (Top-Cat) [inline Linux/LinuxSpecific.cs]: If you're ignoring an exception at minimum I'd add a comment as to why
ie "Ignore errors that occur when no tty is attached"

File: Linux/LinuxSpecific.cs [hunk 2]
```diff
@@ -172,6 +175,13 @@ public string GetCDNFilename()
 
     public string GetDownloadFolder()
     {
+        // _args.Length - 1 because we need to get the arg after
+        for (var i = 0; i < _args.Length - 1; ++i) {
+            if (_args[i] == "--cmldownloadfolder") {
```
Comment (Top-Cat) [inline Linux/LinuxSpecific.cs]: This seems overly verbose to me. What about just `--dir`?

**Review by Top-Cat — CHANGES_REQUESTED** [review]
Just a couple small changes 🙏

File: Linux/LinuxSpecific.cs (hunk 1 above)
Comment (FallenCharlotte) [reply Linux/LinuxSpecific.cs]: No longer relies on a try/catch, actually checks for a console instead

File: Linux/LinuxSpecific.cs (hunk 2 above)
Comment (FallenCharlotte) [reply Linux/LinuxSpecific.cs]: Done
